import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

// Deliberately without @stencil/eslint-plugin, which the library does use. That
// plugin pulls oxlint and eslint-plugin-react in as peers, and this repo defines
// exactly one Stencil component -- the cost outweighs what it would catch here.
export default tseslint.config(
  {
    ignores: [
      'www/**',
      'node_modules/**',
      // Generated by Stencil on every build, in Stencil's own style.
      'src/components.d.ts',
      // Workbox service worker template: runs in a worker scope against globals
      // (`self`, `workbox`, `importScripts`) that this config does not declare.
      'src/sw.js',
    ],
  },
  tseslint.configs.recommended,
  prettierConfig,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
  {
    // Stencil compiles JSX with `jsxFactory: "h"`, so every .tsx file imports
    // `h` and never references it by name. Without this the import reads as
    // unused, and removing it breaks the build.
    files: ['**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^h$' }],
    },
  },
);
